import Head from 'next/head'
import Image from 'next/image'

export default function Home() {

  function devToolsClick(e) {
    e.preventDefault();
    e.currentTarget.nextElementSibling.hidden = !e.currentTarget.nextElementSibling.hidden;
  }

  return (
    <div className="container">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid-layout mt-40">
        <h1 className="grid-col-span-4 md:grid-col-span-8 lg:grid-col-span-12 f-h1">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="grid-col-span-4 md:grid-col-span-4 lg:grid-col-span-6 f-body">
          Get started by editing{' '}
          <code className="code">pages/index.tsx</code>
        </p>

        <div className="grid-col-span-4 md:grid-col-span-4 lg:grid-col-span-6 f-body">
          <a href="https://nextjs.org/docs" className="block mt-40">
            <h2 className="f-h3">Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className="block mt-40">
            <h2 className="f-h3">Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="block mt-40"
          >
            <h2 className="f-h3">Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className="block mt-40"
          >
            <h2 className="f-h3">Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className="mt-40">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
      <div className="dev-tools">
          <button className="dev-tools-toggle" onClick={devToolsClick}></button>
          <div className="dev-tools-grid" hidden></div>
      </div>
    </div>
  )
}
